title: Vikarn Bhakri # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Hi! Here's a little about me I am a machine learning and deep learning enthusiast. Currently pursuing a Masters degree in Electrical engineering where I get to specialise and learn all about how to build and apply ML models to real world scenarios. Apart from this I love watching and playing all sorts of sports be it American football, rugby, basketball but my favourite is soccer. <br>
  Second description 
  <br> Currently I am seeking an internship for the summer of 2020 and the coronavirus isnt helping. If you think I would be a good fit feel fre to contact me at Email: vikarnbhakri@gmail.com <br>
  <a href="www.linkedin.com/in/vikarn-bhakri">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
